### ISSUE TITLE
Java Exception on getting 3 Pride cards with 60 Card deck

### ISSUE THREAD

**Issue by Rolli95** [GraysonnG/InfiniteSpire#14]
14:48:41.781 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_144]
	at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2703) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:823) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:418) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
14:48:41.788 INFO core.CardCrawlGame> PAUSE()
14:48:41.788 INFO core.CardCrawlGame> Game shutting down...
14:48:41.789 INFO helpers.FileSaver> Save thread interrupted!
14:48:41.789 INFO helpers.FileSaver> Save thread will die now.

**Comment by GraysonnG** [comment]
What other mods did you have installed?

**Comment by Rolli95** [comment]
Im currently using
basemod
constructMod
infinite spire
replaythespire
sts_alwayswhale

**Comment by GraysonnG** [comment]
I believe the issue you are having is with Replay The Spire, it is a known bug with grinning jar

**Comment by Rolli95** [comment]
OK, thank you very much! appreciated!
