### ISSUE TITLE
Instant crash on lord of anihilation kill

### ISSUE THREAD

**Issue by Jedi515** [GraysonnG/InfiniteSpire#52]
Already happened like 4 times in a row, can't proceed in my infinite simply because it just crashes right when his hp drops down to 0. And then i have to redo entire fight all over. And then it crashes yet again. And again.
Debug log:
```
Exception: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: img/infinitespire/ui/mainMenu/title.png
01:19:58.916 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: img/infinitespire/ui/mainMenu/title.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.load(TextureAtlas.java:244) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:236) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216) ~[desktop-1.0.jar:?]
	at infinitespire.patches.MainMenuPatch.setMainMenuBG(MainMenuPatch.java:43) ~[InfiniteSpire.jar:?]
	at infinitespire.monsters.LordOfAnnihilation.die(LordOfAnnihilation.java:143) ~[InfiniteSpire.jar:?]
	at com.megacrit.cardcrawl.monsters.AbstractMonster.damage(AbstractMonster.java:806) ~[?:?]
	at infinitespire.monsters.LordOfAnnihilation.damage(LordOfAnnihilation.java:107) ~[InfiniteSpire.jar:?]
	at com.megacrit.cardcrawl.actions.common.DamageAction.update(DamageAction.java:93) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:271) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2513) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:881) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:460) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Caused by: java.io.IOException: Error loading pixmap: decoder init failed for stream
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:90) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:146) ~[desktop-1.0.jar:?]
	... 19 more
```
Also not sure if it's base game or any other mod, but it crashes way too often when trying to proceed next act. Always says error in base game loading background image, but who's there to blame

**Comment by GraysonnG** [comment]
I have no idea why that would be happening, all i can recommend is to redownload the mod because it seems like that jar might be corrupted.
