### ISSUE TITLE
Mass of Shapes crash on Multi-Hit AOE

### ISSUE THREAD

**Issue by DanielWieder** [GraysonnG/InfiniteSpire#53]
When fighting Mass of Shapes, whirlwind causes a monster to spawn, and then on the next hit crashes the game with the following error.

I originally found it using Double Tap + Whirlwind, but was later able to replicate it with just whirlwind. I think that any effect that hits all enemies multiple times could cause the same effect.

It looks like this is because when the number of monsters changes, it doesn't get properly updated everywhere.

Exception: java.lang.ArrayIndexOutOfBoundsException: 2
04:57:25.386 ERROR core.CardCrawlGame> Exception caught
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.update(DamageAllEnemiesAction.java:86) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:271) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2513) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:881) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:460) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by GraysonnG** [comment]
I am aware of this bug and it will be fixed very soon  :P
