### ISSUE TITLE
Portal Room causes crash when returning from Quest Log

### ISSUE THREAD

**Issue by Sinistralis** [GraysonnG/InfiniteSpire#55]
- Enter Portal Room (Replay the Spire)

- Accept event

- Open Quest Log

- Return from Quest Log

I'm guessing the Portal Room doesn't have a 'previous state' type entry, as exiting the quest menu tends to put you at the 'result' screen of the previous encounter.

Not sure if this bug is for you or for Replay, so logging it to both.

**Comment by DanielWieder** [comment]
I just encountered this. Here is the exception in case it helps.

Exception: java.lang.NullPointerException
06:10:26.764 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:225) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:51) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.mod.replay.rooms.TeleportRoom.update(TeleportRoom.java:63) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2528) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:881) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:460) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:

**Comment by Sinistralis** [comment]
You can work around this by entering the next room immediately before doing anything else btw for anyone else who is running into this.

**Comment by GraysonnG** [comment]
I believe this is a bug with replay. I will let the author know!
