### ISSUE TITLE
Game crashed during fight

### ISSUE THREAD

**Issue by Fizz78** [GraysonnG/InfiniteSpire#77]
During normal Beaked the Cultist fight game crashed. Most probably due to incompatibility between different mods

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (01-03-2019)
 - ModTheSpire (3.7.2)
Mod list:
 - basemod (5.6.0)
 - stslib (1.11.0)
 - sts-mod-the-blackbeard (1.6.3)
 - ReplayTheSpireMod (1.3.12)
 - hubris (0.19.0)
 - coloredmap (2.2.0)
 - infinitespire (0.10.1)
 - gatherermod (0.5.0)
 - SpikesRelics (0.023)
 - GluttonMod (1.1.0)
 - Slimebound (1.0.8)
 - beakedthecultist-sts (0.6.0)
 - MysticMod (0.15.0)
 - relicsorter (1.1.2)
 - conspire (1.5.4)
 - HighlightPath (0.0.3)
 - TS05_Marisa (0.14.7)
 - constructmod (1.0)
 - chronomuncher (0.10.8)

```
22:21:43.524 INFO dungeons.AbstractDungeon> MONSTER: Looter
22:21:43.530 INFO monsters.MonsterGroup> MONSTER GROUP getMonster(): Could not find monster: FadingForestBoss
22:21:43.653 INFO basemod.BaseMod> publish on post power apply
22:21:43.653 INFO basemod.BaseMod> powers modified
22:21:43.653 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:21:43.653 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:21:43.855 INFO basemod.BaseMod> publish start battle
22:21:43.855 DEBUG the_gatherer.GathererMod> receiveOnBattleStart started.
22:21:43.855 DEBUG the_gatherer.GathererMod> Last potion used: null
22:21:43.855 DEBUG the_gatherer.GathererMod> receiveOnBattleStart finished.
22:21:44.506 INFO basemod.BaseMod> publishPostDraw
22:21:44.623 INFO basemod.BaseMod> publishPostDraw
22:21:44.738 INFO basemod.BaseMod> publishPostDraw
22:21:44.839 INFO basemod.BaseMod> publishPostDraw
22:21:44.955 INFO basemod.BaseMod> publishPostDraw
22:21:46.205 INFO basemod.BaseMod> publish on card use
22:21:46.205 INFO ThMod.ThMod> ThMod : Card used : beaked:Ceremony ; cost : 2
22:21:46.239 INFO basemod.BaseMod> publish on post power apply
22:21:46.239 INFO basemod.BaseMod> powers modified
22:21:46.239 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:21:46.240 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:21:48.239 INFO basemod.BaseMod> publish on card use
22:21:48.239 INFO ThMod.ThMod> ThMod : Card used : beaked:Strike_Y ; cost : 1
22:21:48.356 INFO slimebound.SlimeboundMod> Patch hit.
22:21:49.956 INFO basemod.BaseMod> publishPreMonsterTurn
22:21:49.956 DEBUG the_gatherer.GathererMod> receivePreMonsterTurn started.
22:21:49.957 DEBUG the_gatherer.GathererMod> Last potion used: null
22:21:49.957 DEBUG the_gatherer.GathererMod> receivePreMonsterTurn finished.
22:21:50.973 INFO slimebound.SlimeboundMod> Patch hit.
22:21:51.139 INFO basemod.BaseMod> publish on Player Lose Block
22:21:51.139 INFO basemod.BaseMod> publishPostEnergyRecharge
22:21:51.139 DEBUG the_gatherer.GathererMod> receivePostEnergyRecharge
22:21:51.272 INFO basemod.BaseMod> publishPostDraw
22:21:51.373 INFO basemod.BaseMod> publishPostDraw
22:21:51.472 INFO basemod.BaseMod> publishPostDraw
22:21:51.589 INFO basemod.BaseMod> publishPostDraw
22:21:51.689 INFO basemod.BaseMod> publishPostDraw
22:21:51.722 INFO basemod.BaseMod> publish on post power apply
22:21:51.722 INFO basemod.BaseMod> powers modified
22:21:51.722 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:21:51.722 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:21:53.355 INFO basemod.BaseMod> publish on card use
22:21:53.355 INFO ThMod.ThMod> ThMod : Card used : beaked:Windmill ; cost : 0
22:21:53.472 INFO slimebound.SlimeboundMod> Patch hit.
22:21:53.505 INFO basemod.BaseMod> publish on post power apply
22:21:53.505 INFO basemod.BaseMod> powers modified
22:21:53.505 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:21:53.505 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:21:54.038 INFO basemod.BaseMod> publish on card use
22:21:54.039 INFO ThMod.ThMod> ThMod : Card used : beaked:CrazyRituals ; cost : 2
22:21:54.073 INFO basemod.BaseMod> publish on post power apply
22:21:54.073 INFO basemod.BaseMod> powers modified
22:21:54.073 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:21:54.073 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:21:54.823 INFO basemod.BaseMod> publish on card use
22:21:54.823 INFO ThMod.ThMod> ThMod : Card used : beaked:Defend_Y ; cost : 1
22:21:55.206 INFO slimebound.SlimeboundMod> Patch hit.
22:21:55.773 INFO basemod.BaseMod> powers modified
22:21:55.773 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:21:55.773 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:21:56.522 INFO basemod.BaseMod> publishPreMonsterTurn
22:21:56.522 DEBUG the_gatherer.GathererMod> receivePreMonsterTurn started.
22:21:56.522 DEBUG the_gatherer.GathererMod> Last potion used: null
22:21:56.522 DEBUG the_gatherer.GathererMod> receivePreMonsterTurn finished.
22:21:57.572 INFO slimebound.SlimeboundMod> Patch hit.
22:21:57.756 INFO basemod.BaseMod> publish on Player Lose Block
22:21:57.756 INFO basemod.BaseMod> publishPostEnergyRecharge
22:21:57.756 DEBUG the_gatherer.GathererMod> receivePostEnergyRecharge
22:21:57.757 INFO beaked.Beaked> Crazy Rituals playing Genetic Algorithm: Gain 1 Block. Permanently increase this card's Block by 2. Exhaust. 
22:21:57.905 INFO basemod.BaseMod> publishPostDraw
22:21:58.006 INFO basemod.BaseMod> publishPostDraw
22:21:58.122 INFO basemod.BaseMod> publishPostDraw
22:21:58.222 INFO basemod.BaseMod> publishPostDraw
22:21:59.073 INFO basemod.BaseMod> publishPostDraw
22:21:59.106 INFO basemod.BaseMod> publish on post power apply
22:21:59.106 INFO basemod.BaseMod> powers modified
22:21:59.106 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:21:59.106 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:22:00.289 INFO basemod.BaseMod> publish on card use
22:22:00.289 INFO ThMod.ThMod> ThMod : Card used : Genetic Algorithm ; cost : 1
Count: 1
22:22:00.889 INFO basemod.BaseMod> publish on card use
22:22:00.889 INFO ThMod.ThMod> ThMod : Card used : beaked:CrazyRituals ; cost : 2
22:22:00.923 INFO basemod.BaseMod> publish on post power apply
22:22:00.923 INFO basemod.BaseMod> powers modified
22:22:00.923 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:22:00.923 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:22:01.405 INFO basemod.BaseMod> publish on card use
22:22:01.405 INFO ThMod.ThMod> ThMod : Card used : beaked:Defend_Y ; cost : 1
22:22:03.106 INFO basemod.BaseMod> publishPreMonsterTurn
22:22:03.106 DEBUG the_gatherer.GathererMod> receivePreMonsterTurn started.
22:22:03.106 DEBUG the_gatherer.GathererMod> Last potion used: null
22:22:03.106 DEBUG the_gatherer.GathererMod> receivePreMonsterTurn finished.
22:22:04.122 INFO slimebound.SlimeboundMod> Patch hit.
22:22:04.272 INFO basemod.BaseMod> publish on Player Lose Block
22:22:04.272 INFO basemod.BaseMod> publishPostEnergyRecharge
22:22:04.272 DEBUG the_gatherer.GathererMod> receivePostEnergyRecharge
22:22:04.273 INFO beaked.Beaked> Crazy Rituals playing Dark Transmutation: Add X random Black cards to your hand. They cost 1 less this round. Purge. 
22:22:04.284 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/cards/ui/512/boss-frame-skill.png
22:22:04.405 INFO basemod.BaseMod> publishPostDraw
22:22:04.506 INFO basemod.BaseMod> publishPostDraw
22:22:04.623 INFO basemod.BaseMod> publishPostDraw
22:22:04.739 INFO basemod.BaseMod> publishPostDraw
22:22:04.855 INFO basemod.BaseMod> publishPostDraw
22:22:04.888 INFO basemod.BaseMod> publish on post power apply
22:22:04.888 INFO basemod.BaseMod> powers modified
22:22:04.889 DEBUG the_gatherer.GathererMod> receivePowersModified started.
22:22:04.889 DEBUG the_gatherer.GathererMod> receivePowersModified finished.
22:22:06.072 INFO basemod.BaseMod> publish on card use
22:22:06.072 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:Dark Transmutation ; cost : -1

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: infinitespire.helpers.CardHelper.getRandomBlackCard()Linfinitespire/abstracts/BlackCard;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: infinitespire.helpers.CardHelper.getRandomBlackCard()Linfinitespire/abstracts/BlackCard;
	at com.megacrit.cardcrawl.mod.replay.actions.unique.BlackTransmuteAction.update(BlackTransmuteAction.java:43)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:283)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2584)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:885)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:436)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by GraysonnG** [comment]
0.10.3 Should have resolved this issue, make sure you get this update from the Steam Workshop.
