### ISSUE TITLE
Crash at rest site having Magic Flask

### ISSUE THREAD

**Issue by WNJStudio** [GraysonnG/InfiniteSpire#85]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at infinitespire.ui.FlaskOption.<init>(FlaskOption.java:20)
	at infinitespire.patches.CampfirePatch$InitializeButtons.Postfix(CampfirePatch.java:27)
	at com.megacrit.cardcrawl.rooms.CampfireUI.initializeButtons(CampfireUI.java:151)
	at com.megacrit.cardcrawl.rooms.CampfireUI.<init>(CampfireUI.java:59)
	at com.megacrit.cardcrawl.rooms.RestRoom.onPlayerEntry(RestRoom.java:35)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2319)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:582)
	at com.megacrit.cardcrawl.dungeons.TheCity.<init>(TheCity.java:89)
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1398)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:861)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by Oxpecker-VMI** [comment]
I'm having the same issue.

**Comment by GraysonnG** [comment]
You guys need to make sure you are using the latest version of Slay the Spire and be subscribed and have the latest version of the Steam Workshop Infinite Spire

**Comment by AvangionQ** [comment]
Same here, please fix ...

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at infinitespire.ui.FlaskOption.<init>(FlaskOption.java:20)
	at infinitespire.patches.CampfirePatch$InitializeButtons.Postfix(CampfirePatch.java:27)
	at com.megacrit.cardcrawl.rooms.CampfireUI.initializeButtons(CampfireUI.java:152)
	at com.megacrit.cardcrawl.rooms.CampfireUI.<init>(CampfireUI.java:59)
	at com.megacrit.cardcrawl.rooms.RestRoom.onPlayerEntry(RestRoom.java:35)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2322)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2182)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2851)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2539)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by AvangionQ** [comment]
> You guys need to make sure you are using the latest version of Slay the Spire and be subscribed and have the latest version of the Steam Workshop Infinite Spire

I'm using 3.6.3 ... which is the latest version available on this site.
If you want me to update, please ask them to upload the new version here ... https://github.com/kiooeht/ModTheSpire/releases
